### ISSUE TITLE
People who already voted this month still receive the "about to close" email

### ISSUE THREAD

**Issue by moreau-nicolas** [Zenika/humeur-du-mois-2018#129] opened 2020-05-04 07:55 UTC
People who already voted this month still receive the "about to close" email. They shouldn't.

Worse, they are encouraged to vote but when they try to do so they receive an error message when clicking on the "vote" button.

**Comment by hgwood** [comment] 2020-05-04 10:02
I don't think there is any bug here, the app works as intended. :)

> People who already voted this month still receive the "about to close" email. They shouldn't.

This is a feature request.

We do this because it's a *lot* simpler, we just send one email to `config.features.reminders.voting_campaign_starts.recipient` (a mailing list of all users). If we were to send this email only to people who haven't voted, we'd need to send individual emails, with retries and all. I'm not sure I want to venture into this.

> when they try to do so they receive an error message when clicking on the "vote" button.

This is another feature request.

We do this because checking beforehand that the user has not already voted would incur a network request and increase loading time, which is already long. However I guess we could include this info in the existing request that checks that votes are open. I'd be OK with that. @Ked57 Could you create a new issue and tackle it?

**Comment by Ked57** [comment] 2020-05-04 10:22
Done 😄 #130

**Comment by hgwood** [comment] 2020-05-04 11:20
> We do this because it's a lot simpler, we just send one email to config.features.reminders.voting_campaign_starts.recipient (a mailing list of all users). If we were to send this email only to people who haven't voted, we'd need to send individual emails, with retries and all. I'm not sure I want to venture into this.

Actually I didn't think this through. We do not need to send n emails, we can send one email to n recipients, and that would be fine. The real problem for this feature is that votes are anonymous, the app can't know who has already voted or not.

**Comment by hgwood** [comment] 2020-05-04 11:26
> The real problem for this feature is that votes are anonymous, the app can't know who has already voted or not.

Well actually (I'm rediscovering this app 😅), this is incorrect. There is no anonymisation. So I think there is nothing preventing us from not sending the reminder to people who have voted. We can try.

@Ked57 Could you also create a new issue for this? Then this one can be closed.

**Comment by Ked57** [comment] 2020-05-04 12:01
Done #131

**Comment by hgwood** [comment] 2020-05-04 12:30
Thanks. Closing in favor of #130 and #131.

**Closed by hgwood** 2020-05-04 12:30 UTC
